### ISSUE TITLE
BrokenPipeError for non-ASCII chars

### ISSUE THREAD

**Issue by EasyHax** [plasticuproject/cleverbotfree#1]
Hi,

```
Traceback (most recent call last):
  File "T:\Programme\VisualStudio\SDK\Python36_64\cleverbot.py", line 12, in <module>
    print(cb.single_exchange(msg) + "{end}")
  File "T:\Programme\Python27\lib\site-packages\cleverbotfree\cbfree.py", line 113, in single_exchange
    self.send_input(userInput)
  File "T:\Programme\Python27\lib\site-packages\cleverbotfree\cbfree.py", line 61, in send_input
    except BrokenPipeError:
NameError: global name 'BrokenPipeError' is not defined
```

```
import cleverbotfree.cbfree
import sys
cb = cleverbotfree.cbfree.Cleverbot()

msg = "é"
print(cb.single_exchange(msg))
```

Any idea ? Thanks in advance.

**Comment by plasticuproject** [comment]
`
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cleverbotfree.cbfree
>>> import sys
>>> cb = cleverbotfree.cbfree.Cleverbot()
>>> 
>>> msg = "é"
>>> print(cb.single_exchange(msg))
What would you say if I asked you a silly question?
>>> 
`

I don't know what to tell you. I can't replicate your problem. If you have a bad connection sometimes you will get that error, as it's posting form data and parsing the official Cleverbot web page for the response data. Also I haven't tested this module on Windows, only Linux.
