### ISSUE TITLE
Bot constantly timing out after the first few messages

### ISSUE THREAD

**Issue by RealSkyr0** [plasticuproject/cleverbotfree#18]
As title said, bot keeps timing out after the first few messages, then after a while it starts working again and at some point starts timing out again. Is this just a cleverbot issue?
log:

![image](https://user-images.githubusercontent.com/44062109/124379084-944dfa00-dcbd-11eb-96d9-d05639161854.png)

**Comment by plasticuproject** [comment]
@RealSkyr0 Not able to reproduce errors with example code:
![Screenshot-07-04-2021-08-12](https://user-images.githubusercontent.com/19690649/124384554-c9e3ea80-dc9f-11eb-815e-5c696af368e7.png)
![Screenshot-07-04-2021-08-28](https://user-images.githubusercontent.com/19690649/124385002-e4b75e80-dca1-11eb-877d-3c49453c2e0a.png)

**Comment by RealSkyr0** [comment]
Issue occurred on the JS library, does that matter? Might just be my server network speed or code too..

**Comment by RealSkyr0** [comment]
Ooh my bad I'm on the wrong github repo lol
