### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by bakarali64** [plasticuproject/cleverbotfree#20]
bot = c_b.single_exchange(user_input)

**Comment by GitHubEmploy** [comment]
How do you set playwright into headless mode?

**Comment by plasticuproject** [comment]
> Update: <img alt="Screen Shot 2021-10-20 at 9 21 33 PM" width="1461" src="https://user-images.githubusercontent.com/65371337/138211081-ddf6e5be-a1ca-4ef3-beb5-9a960458394f.png">
> 
> There's a warning you have to click before you can start using it

That's always been there and I've never had to automate that click before, it would still load the needed JavaScript function, and still does in headed mode. Pretty sure a click is not needed still.

**Comment by plasticuproject** [comment]
Feel free to play around in headed/debug mode and see if you can figure it out. I know they are taking measures to break these unauthorized wrappers and automated tools as it's cutting into their API subscription revenue 🤷 . I've seen them personally comment on libraries like this one.

**Comment by GitHubEmploy** [comment]
Also, its giving me this error:
<img width="1194" alt="Screen Shot 2021-10-21 at 7 46 03 PM" src="https://user-images.githubusercontent.com/65371337/138385088-e0402071-1f63-4a54-bce7-7e4ed5154161.png">

If I dont click the message. Any way to fix this?
Also, the accept can be done by executing the noteok() function in console:
<img width="639" alt="Screen Shot 2021-10-21 at 7 47 19 PM" src="https://user-images.githubusercontent.com/65371337/138385187-543c8163-7c0a-4194-a3a9-152a0aa20f95.png">

If you can do this through playwright, this would probably work.

Also, is there any way to do this through selenium?

**Comment by plasticuproject** [comment]
I already explained that you don't need to click that to load the JS script and call the function, that's not the issue:
![cb](https://user-images.githubusercontent.com/19690649/138385679-f2ddd7db-b4a6-47fa-acfa-a60d61bdcbda.png)

> Also, is there any way to do this through selenium?
I used selenium in the version 1.x, it worked for a long time but they started detecting it so I re-wrote it to use playwright. Take a look at the closed issues and you will see.

**Comment by GitHubEmploy** [comment]
Is it okay if you can give me the old selenium version of that code? Just curious on how you implemented it.
