### ISSUE TITLE
The package doesn't work

### ISSUE THREAD

**Issue by Carlos-SJS** [plasticuproject/cleverbotfree#22]
I installed the cleberbotfree package, aswell as the playwright firefox, but when i try the example code it doesn't work and shows an error:
![image](https://user-images.githubusercontent.com/62165753/140635583-3b5fd7a3-856b-4726-8f99-d6b9547d7192.png)

So ineed some help, o know if i doing something wrong or what. Thanks in advance

**Comment by plasticuproject** [comment]
Yes they did something to break it. It was briefly discussed here #20 . I've just been too busy to figure out what was changed to break this. Feel free to poke around and if you get anything working submit a PR or let me know.

**Comment by Carlos-SJS** [comment]
I was trying stuff, and i seen in no headless mode, the error apears is before the page loads, so i added a sleep(1) before the cleverbot.sendAI() call, and now it works, so probably, the error was because the page didn't load quick enough. So probably the fix could be just play arround with the sleep time to get it as tiny as posible but still let the page load

**Comment by RealSoerensen** [comment]
I also have this issue

**Comment by mbledek** [comment]
> I was trying stuff, and i seen in no headless mode, the error apears before the page loads, so i added a sleep(1) before the cleverbot.sendAI() call, and now it works, so probably, the error was because the page didn't load quick enough. So probably the fix could be just play arround with the sleep time to get it as tiny as posible but still let the page load

This works for me

**Comment by PublicVoidUpdate** [comment]
What cleverbot.sendAI? I can't find the line in either of the examples

**Comment by mbledek** [comment]
> What cleverbot.sendAI? I can't find the line in either of the examples

It's not in the example. You have to change it in the __init__.py from cleverbotfree package

**Comment by PublicVoidUpdate** [comment]
Could someone just comment the altered file? I'm not good with python

**Comment by plasticuproject** [comment]
Pip install the new package, v2.3.3, and follow directions. Should work now.
