### ISSUE TITLE
Only works the first fifteen times exactly.

### ISSUE THREAD

**Issue by HTahboub** [plasticuproject/cleverbotfree#3]
Either this hasn't been tested enough or this just happens on my machine (iMac). In a conversation like this one:-

> User: 1
> Cleverbot: 2
> User: 3
> Cleverbot: 4
> User: 5
> Cleverbot: 6
> User: 7
> Cleverbot: 8
> User: 9
> Cleverbot: 10
> User: 11
> Cleverbot: 12
> User: 13
> Cleverbot: 14
> User: 15

I always get this error right after the fifteenth:-

```
Traceback (most recent call last):
  File "session_chat.py", line 28, in <module>
    main()
  File "session_chat.py", line 22, in main
    bot = cb.get_response()
  File "......../cbfree.py", line 88, in get_response
    if line.text != newLine and newLine.text != ' ' and newLine.text != '':
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <p id="line1" class=""> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed.
```

I urgently need a fix for this. Thanks.

**Comment by plasticuproject** [comment]
@HTahboub 
I created this as a way to side-step their paid API service by directly interacting with their website DOM. It looks like they have recently changed the functionality to use some kind of pagination when your conversation reaches a certain limit,  i.e. `url + /?1`, `url + /?2`, etc., breaking this library. I'll work on making a fix for this soon, or if you would like to take a stab at it you can issue a Pull Request and I will review it. Thank you for bringing this to my attention.

**Comment by plasticuproject** [comment]
Should be fixed now, updated repository and PyPi. Closing this issue. Please leave a commit if you are still having problems with it and I will reopen the issue.

**Comment by HTahboub** [comment]
Thank you so much—this is perfect.
